ssh_authorized_keys:
- github:stelb

boot_cmd:
# make nfs client work
- mkdir -p /var/lib/nfs/sm
- /usr/sbin/rc-update add nfsclient
# democratic-csi mounts localtime from host...
- ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

k3os:
  server_url: https://k3os-server:6443
  token: stelb:lab
  modules:
  - wireguard
  - nfs
