ssh_authorized_keys:
- github:stelb
hostname: k3os-server

boot_cmd:
- mkdir -p /var/lib/nfs/sm
- /usr/sbin/rc-update add nfsclient
- ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

k3os:
  token: stelb:lab
  modules:
  - wireguard
  - nfs
  k3s_args:
  - server
  - --disable
  - servicelb
